language: node_js - 6.11.3
install: npm install
branches:
  only:
  - master
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: EbLenlSZ61jInvqc8RfjEycbw0aF7Opa/R7h0wdY2X0nxap4vpydU8MiE2d1YKcd5N/zWVfXOhke3MMHatz8Wcg304rl7+JXX1SMh/hsRDJ8dOef3rtVKUB4yob/W4LGoWBM/uocWUCDlWtvMsFetHUfqVWw+fdgPPPQjFYXZWF/MyGNLt+nf49MMCfbsfbZGu08WC/CFYkzLxtOBT57Ysrs2NG9mrHkFWs2DHlXzVaA7yWDyeVpzNL4sh6db7DYK7bAB3MpB3OtIKO64C2hoZhyoy4bbN4rthqXWq3R7wOYZgf6GAk3HLxDU+XUHv0rdnZEFM2XNsblDhC6ZT4SxNiMjB+6HVT6RgmDX1YdSurRCriwdF023NL7EF8pjffPgaJ8PtieaAvu2MRpIgW7y8JbLHh0JGQGmV4zP0GFDko/8RPyTSyD+o2i0eNOHiwHIac5xbxS7xyBxiYp5n8ZToX8aZc+ThI9HjfMEQDT0e+a7n+VbgkptLEZOBo218SgEFzIzbABhMayVEn7inUV/V5sM8QeS6bCJotxnDpEtBXeUGcTYDWAzdvHX3ltXn9xjt8l+pA4mbzJndKsYmJhwV2JcHFjqDRcq+vbV/ZCiJMW+/9nSWI31VL31hXz5W9t9mQK/LYkq3SKt4aSMhQyRQNoyrKgZ2iEAhNiifWCtI8=
  app: daily-tarot-staging
  on:
    repo: davidwkaiser/daily-tarot
