language: node_js - 6.11.3
install: npm install
branches:
  only:
  - master
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: hUHCu9oViaOBAPOHbkGt0h/iwxgk4b3b6iw1nl0bw1kprBtBswJnYOgxcO7C1enXkHSTwrn69ojj7dpZrgJNmK5sb5d9c0twETPklzv8uDLquYetrbhVvLySmBqNsm3VU2LnFnTn8XHhwTWpw2gRwC6Y8VGJf/IbWGPmZ8zJTPPY9cMu/bsLwav+BaJ8tmWbQpTBTKbTWm/uDHmQWk4118k3FbHCMqwAMWI5A9K16l0YW3KyXblSlFT31mYprsK3y5Qx8pFejrulMo+/2JTJIx8WVpXawgD7ibVp5eAD4F6qibAb03YbtBp68rFwM0JZOZ1p8HsRluMvPf+n8t9sq3fFIJzVI8mWsPeY0SGyoJgxgz+SX/kLxEy/6rJvHJLgxyiscpfFZx6mNJExsbqj1pkKWAm88LSAnW17aVXgHrBqa0lNE48/oWNiEhGrxcX9RshFPrhyA+EnL2inZK7YimzxJA5JLW+EAgzN5C1dRH0hPZscqaBbefzlMUqmH9cGHTc7zl4VUBLuWeeZvr5D4dOgyj8Gv1cduT2LtRkW8woCHgDeNi2GcjsKFAgb92SgcOIm1IwrFNYAjIZJTUGXe2xun0Pe1EDiDNVp3qH/5/tRPiz0+OBHttOODGhpls9stZ+mF3Ncu7+36vuPHdLmG3zWP5SuMYHZne+7OtMIBhc=
  app: daily-tarot-staging
  on:
    repo: davidwkaiser/daily-tarot
