exports.cards = [
  {name:"The Fool", image: "maj00.jpg", keywords: ["Innocence", "New Beginnings", "Optimism"]},
  {name:"The Magician", image: "maj01.jpg", keywords: ["Power", "Presence", "Clarity"]},
  {name:"The High Priestess", image: "maj02.jpg", keywords: ["Intuition", "Subconscious", "Reflection"]},
  {name:"The Empress", image: "maj03.jpg", keywords: ["Abundance", "Mothering", "Sensuality"]},
  {name:"The Emperor", image: "maj04.jpg", keywords: ["Order", "Accountability", "Authority", "Fathering"]},
  {name:"The Hierophant", image: "maj05.jpg", keywords: ["Formal Learning", "Conformity", "Structure"]},
  {name:"The Lovers", image: "maj06.jpg", keywords: ["Love", "Attraction", "Sexuality", "Strong Boundaries"]},
  {name:"The Chariot", image: "maj07.jpg", keywords: ["Will", "Hard Power" ]},
  {name:"Strength", image: "maj08.jpg", keywords: ["Soft Power", "Influence"]},
  {name:"The Hermit", image: "maj09.jpg", keywords: ["Introspection", "Searching", "Guidance", "Solitude"]},
  {name:"Wheel of Fortune", image: "maj10.jpg", keywords: ["Destiny", "Turning Point", "Movement", "Personal Vision"]},
  {name:"Justice", image: "maj11.jpg", keywords: ["Justice", "Responsibility", "Decision", "Cause and Effect"]},
  {name:"The Hanged Man", image: "maj12.jpg", keywords: ["Letting Go", "Reversal", "Suspension", "Sacrifice"]},
  {name:"Death", image: "maj13.jpg", keywords: ["Ending", "Transition", "Elimination", "Inexorable Forces"]},
  {name:"Temperance", image: "maj14.jpg", keywords: ["Temperance", "Balance", "Health", "Combination"]},
  {name:"The Devil", image: "maj15.jpg", keywords: ["Bondage", "Materialism", "Ignorance", "Hopelessness"]},
  {name:"The Tower", image: "maj16.jpg", keywords: ["Sudden Change", "Release", "Downfall", "Revelation"]},
  {name:"The Star", image: "maj17.jpg", keywords: ["Hope", "Inspiration", "Generosity", "Serenity"]},
  {name:"The Moon", image: "maj18.jpg", keywords: ["Moon", "Illusion", "Imagination", "Bewilderment"]},
  {name:"The Sun", image: "maj19.jpg", keywords: ["Enlightenment", "Greatness", "Vitality", "Assurance"]},
  {name:"Judgement", image: "maj20.jpg", keywords: ["Judgment", "Rebirth", "Inner Calling", "Absolution"]},
  {name:"The World", image: "maj21.jpg", keywords: ["Integration", "Accomplishment", "Involvement", "Fulfillment"]},
  {name:"Ace of Wands", image: "wands01.jpg", keywords: ["Creative Force", "Enthusiasm", "Confidence", "Courage"]},
  {name:"Two of Wands", image: "wands02.jpg", keywords: ["Personal Power", "Boldness", "Originality"]},
  {name:"Three of Wands", image: "wands03.jpg", keywords: ["Exploration", "Foresight", "Leadership"]},
  {name:"Four of Wands", image: "wands04.jpg", keywords: ["Celebration", "Freedom", "Excitement"]},
  {name:"Five of Wands", image: "wands05.jpg", keywords: ["Disagreement", "Competition", "Hassles"]},
  {name:"Six of Wands", image: "wands06.jpg", keywords: ["Triumph", "Acclaim", "Pride"]},
  {name:"Seven of Wands", image: "wands07.jpg", keywords: ["Aggression", "Defiance", "Conviction"]},
  {name:"Eight of Wands", image: "wands08.jpg", keywords: ["Quick Action", "Conclusion", "News"]},
  {name:"Nine of Wands", image: "wands09.jpg", keywords: ["Defensiveness", "Perseverance", "Stamina"]},
  {name:"Ten of Wands", image: "wands10.jpg", keywords: ["Overextending", "Burdens", "Struggle"]},
  {name:"Page of Wands", image: "wands11.jpg", keywords: []},
  {name:"Knight of Wands", image: "wands12.jpg", keywords: []},
  {name:"Queen of Wands", image: "wands13.jpg", keywords: []},
  {name:"King of Wands", image: "wands14.jpg", keywords: []},
  {name:"Ace of Cups", image: "cups01.jpg", keywords: []},
  {name:"Two of Cups", image: "cups02.jpg", keywords: []},
  {name:"Three of Cups", image: "cups03.jpg", keywords: []},
  {name:"Four of Cups", image: "cups04jpg", keywords: []},
  {name:"Five of Cups", image: "cups05.jpg", keywords: []},
  {name:"Six of Cups", image: "cups06.jpg", keywords: []},
  {name:"Seven of Cups", image: "cups07.jpg", keywords: []},
  {name:"Eight of Cups", image: "cups08.jpg", keywords: []},
  {name:"Nine of Cups", image: "cups09.jpg", keywords: []},
  {name:"Ten of Cups", image: "cups10.jpg", keywords: []},
  {name:"Page of Cups", image: "cups11.jpg", keywords: []},
  {name:"Knight of Cups", image: "cups12.jpg", keywords: []},
  {name:"Queen of Cups", image: "cups13.jpg", keywords: []},
  {name:"King of Cups", image: "cups14.jpg", keywords: []},
  {name:"Ace of Swords", image: "swords01.jpg", keywords: []},
  {name:"Two of Swords", image: "swords02.jpg", keywords: []},
  {name:"Three of Swords", image: "swords03.jpg", keywords: []},
  {name:"Four of Swords", image: "swords04.jpg", keywords: []},
  {name:"Five of Swords", image: "swords05.jpg", keywords: []},
  {name:"Six of Swords", image: "swords06.jpg", keywords: []},
  {name:"Seven of Swords", image: "swords07.jpg", keywords: []},
  {name:"Eight of Swords", image: "swords08.jpg", keywords: []},
  {name:"Nine of Swords", image: "swords09.jpg", keywords: []},
  {name:"Ten of Swords", image: "swords10.jpg", keywords: []},
  {name:"Page of Swords", image: "swords11.jpg", keywords: []},
  {name:"Knight of Swords", image: "swords12.jpg", keywords: []},
  {name:"Queen of Swords", image: "swords13.jpg", keywords: []},
  {name:"King of Swords", image: "swords14.jpg", keywords: []},
  {name:"Ace of Pentacles", image: "pents01.jpg", keywords: []},
  {name:"Two of Pentacles", image: "pents02.jpg", keywords: []},
  {name:"Three of Pentacles", image: "pents03.jpg", keywords: []},
  {name:"Four of Pentacles", image: "pents04.jpg", keywords: []},
  {name:"Five of Pentacles", image: "pents05.jpg", keywords: []},
  {name:"Six of Pentacles", image: "pents06.jpg", keywords: []},
  {name:"Seven of Pentacles", image: "pents07.jpg", keywords: []},
  {name:"Eight of Pentacles", image: "pents08.jpg", keywords: []},
  {name:"Nine of Pentacles", image: "pents09.jpg", keywords: []},
  {name:"Ten of Pentacles", image: "pents10.jpg", keywords: []},
  {name:"Page of Pentacles", image: "pents11.jpg", keywords: []},
  {name:"Knight of Pentacles", image: "pents12.jpg", keywords: []},
  {name:"Queen of Pentacles", image: "pents13.jpg", keywords: []},
  {name:"King of Pentacles", image: "pents14.jpg", keywords: []},
]