exports.cards = [
  {name:"The Fool", image: "maj00.jpg", keywords: ["Innocence", "New Beginnings", "Optimism"]},
  {name:"The Magician", image: "maj01.jpg", keywords: ["Power", "Presence", "Clarity"]},
  {name:"The High Priestess", image: "maj02.jpg", keywords: ["Intuition", "Subconscious", "Reflection"]},
  {name:"The Empress", image: "maj03.jpg", keywords: ["Abundance", "Mothering", "Sensuality", "Nature"]},
  {name:"The Emperor", image: "maj04.jpg", keywords: ["Order", "Accountability", "Authority", "Fathering"]},
  {name:"The Hierophant", image: "maj05.jpg", keywords: ["Formal Learning", "Conformity", "Structure"]},
  {name:"The Lovers", image: "maj06.jpg", keywords: ["Love", "Attraction", "Sexuality", "Strong Boundaries"]},
  {name:"The Chariot", image: "maj07.jpg", keywords: ["Will", "Hard Power" ]},
  {name:"Strength", image: "maj08.jpg", keywords: ["Soft Power", "Influence"]},
  {name:"The Hermit", image: "maj09.jpg", keywords: ["Introspection", "Withdrawal", "Searching", "Solitude"]},
  {name:"Wheel of Fortune", image: "maj10.jpg", keywords: ["Destiny", "Turning Point", "Larger Forces At Work"]},
  {name:"Justice", image: "maj11.jpg", keywords: ["Justice", "Responsibility", "Cause and Effect"]},
  {name:"The Hanged Man", image: "maj12.jpg", keywords: ["Letting Go", "Reversal", "Sacrifice"]},
  {name:"Death", image: "maj13.jpg", keywords: ["Ending", "Change", "Humility"]},
  {name:"Temperance", image: "maj14.jpg", keywords: ["Temperance", "Balance"]},
  {name:"The Devil", image: "maj15.jpg", keywords: ["Illusion", "Materialism", "Ignorance", "Self-Desctructive Choices"]},
  {name:"The Tower", image: "maj16.jpg", keywords: ["Shattering the Status Quo", "Ego Death", "Dramatic Change", "Loss of Illusions"]},
  {name:"The Star", image: "maj17.jpg", keywords: ["Hope", "Serenity", "Generosity"]},
  {name:"The Moon", image: "maj18.jpg", keywords: ["Illusion", "Imagination", "Charm"]},
  {name:"The Sun", image: "maj19.jpg", keywords: ["Enlightenment", "Power", "On Top Of The World"]},
  {name:"Judgement", image: "maj20.jpg", keywords: ["Judgment", "Forgiveness", "Rebirth"]},
  {name:"The World", image: "maj21.jpg", keywords: ["Integration", "Fulfillment", "Connectedness"]},
  {name:"Ace of Wands", image: "wands01.jpg", keywords: ["Creative Force", "Enthusiasm", "Confidence", "Courage"]},
  {name:"Two of Wands", image: "wands02.jpg", keywords: ["Personal Power", "Boldness", "Originality"]},
  {name:"Three of Wands", image: "wands03.jpg", keywords: ["Exploration", "Foresight", "Leadership"]},
  {name:"Four of Wands", image: "wands04.jpg", keywords: ["Celebration", "Freedom", "Excitement"]},
  {name:"Five of Wands", image: "wands05.jpg", keywords: ["Disagreement", "Competition", "Hassles"]},
  {name:"Six of Wands", image: "wands06.jpg", keywords: ["Triumph", "Acclaim", "Pride"]},
  {name:"Seven of Wands", image: "wands07.jpg", keywords: ["Aggression", "Defiance", "Conviction"]},
  {name:"Eight of Wands", image: "wands08.jpg", keywords: ["Quick Action", "Conclusion", "News"]},
  {name:"Nine of Wands", image: "wands09.jpg", keywords: ["Defensiveness", "Perseverance", "Stamina"]},
  {name:"Ten of Wands", image: "wands10.jpg", keywords: ["Overextending", "Burdens", "Struggle"]},
  {name:"Page of Wands", image: "wands11.jpg", keywords: ["Explore Creativity", "Be Enthusiastic", "Trust Confidence", "Have Courage"]},
  {name:"Knight of Wands", image: "wands12.jpg", keywords: ["Charming ~ Superficial", "Self-Confident ~ Cocky", "Daring ~ Foolhardy", "Adventurous ~ Restless", "Passionate ~ Hot-Tempered"]},
  {name:"Queen of Wands", image: "wands13.jpg", keywords: ["Attractive", "Energetic", "Cheerful", "Popular"]},
  {name:"King of Wands", image: "wands14.jpg", keywords: ["Creative", "Forceful", "Charismatic", "Bold"]},
  {name:"Ace of Cups", image: "cups01.jpg", keywords: ["Emotional Force", "Intiution"]},
  {name:"Two of Cups", image: "cups02.jpg", keywords: ["Attraction", "Connection"]},
  {name:"Three of Cups", image: "cups03.jpg", keywords: ["Friendship", "Community", "Joy"]},
  {name:"Four of Cups", image: "cups04jpg", keywords: ["Apathy", "Turning Within", "Introspection", "Obliviousness"]},
  {name:"Five of Cups", image: "cups05.jpg", keywords: ["Grief", "Loss", "Focus on the Negative"]},
  {name:"Six of Cups", image: "cups06.jpg", keywords: ["Innocence", "Childhood", "Sweetness"]},
  {name:"Seven of Cups", image: "cups07.jpg", keywords: ["Options", "Distractions", "Deception"]},
  {name:"Eight of Cups", image: "cups08.jpg", keywords: ["Letting Go", "Moving On", "Detachment"]},
  {name:"Nine of Cups", image: "cups09.jpg", keywords: ["Pleasure", "Self-Satisfaction", "Wish Card"]},
  {name:"Ten of Cups", image: "cups10.jpg", keywords: ["Family", "Love", "Joy"]},
  {name:"Page of Cups", image: "cups11.jpg", keywords: ["Emotion", "Intuition", "Love"]},
  {name:"Knight of Cups", image: "cups12.jpg", keywords: ["Intuitive ~ Haphazard", "Romantic ~ Saccharine", "Emotional ~ Self-Absorbed"]},
  {name:"Queen of Cups", image: "cups13.jpg", keywords: ["Understanding", "Empathetic", "Sweet", "Wise"]},
  {name:"King of Cups", image: "cups14.jpg", keywords: ["Diplomatic", "Connected", "Patient"]},
  {name:"Ace of Swords", image: "swords01.jpg", keywords: ["Mental Force"]},
  {name:"Two of Swords", image: "swords02.jpg", keywords: ["Feeling Blocked", "Willful Blindness"]},
  {name:"Three of Swords", image: "swords03.jpg", keywords: ["Loneliness", "Heartbreak", "Abandonment", "Betrayal"]},
  {name:"Four of Swords", image: "swords04.jpg", keywords: ["Rest", "Preparation", "The Calm Before the Storm"]},
  {name:"Five of Swords", image: "swords05.jpg", keywords: ["Conflict", "Self-Interest", "Loss of Connection"]},
  {name:"Six of Swords", image: "swords06.jpg", keywords: ["Moving On", "Escape", "Seeking Refuge"]},
  {name:"Seven of Swords", image: "swords07.jpg", keywords: ["Running Away", "Breaking Rules", "Theft"]},
  {name:"Eight of Swords", image: "swords08.jpg", keywords: ["Captivity", "Bound", "Stuck"]},
  {name:"Nine of Swords", image: "swords09.jpg", keywords: ["Guilty Conscience", "Painful Memories", "Repression"]},
  {name:"Ten of Swords", image: "swords10.jpg", keywords: ["Victimhood", "Drama", "Dark Humor"]},
  {name:"Page of Swords", image: "swords11.jpg", keywords: ["Smart", "Ethical", "Be Straightforward"]},
  {name:"Knight of Swords", image: "swords12.jpg", keywords: ["Straightforward ~ Blunt", "Rational ~ Lacking Empathy", "Smart ~ Pointy-Headed", "Ethical ~ Self-Righteous"]},
  {name:"Queen of Swords", image: "swords13.jpg", keywords: ["No-Nonsense", "Astute", "Keen", "Articulate","Sees Through BS"]},
  {name:"King of Swords", image: "swords14.jpg", keywords: ["Smart", "Just", "Intellecutal", "Straightforward", "Master of Words"]},
  {name:"Ace of Pentacles", image: "pents01.jpg", keywords: ["Material Force", "Practical Matters", "Managing Things Well"]},
  {name:"Two of Pentacles", image: "pents02.jpg", keywords: ["Ease", "Grace", "Balance"]},
  {name:"Three of Pentacles", image: "pents03.jpg", keywords: ["Teamwork", "Cooperation", "Different Spheres Coming Together"]},
  {name:"Four of Pentacles", image: "pents04.jpg", keywords: ["Maintaining Control", "Hanging On To Something"]},
  {name:"Five of Pentacles", image: "pents05.jpg", keywords: ["Suffering", "Deprivation", "Time In THe Wilderness"]},
  {name:"Six of Pentacles", image: "pents06.jpg", keywords: ["To Have and Have Not", "Judging Worthiness"]},
  {name:"Seven of Pentacles", image: "pents07.jpg", keywords: ["Stepping Back", "Assessing"]},
  {name:"Eight of Pentacles", image: "pents08.jpg", keywords: ["Persistence", "Craftmanship", "Focus", "Enjoying One's Work"]},
  {name:"Nine of Pentacles", image: "pents09.jpg", keywords: ["Mastering Animal Instincts", "Having Nice Things", "Self-Control"]},
  {name:"Ten of Pentacles", image: "pents10.jpg", keywords: ["Wealth", "Being Conservative"]},
  {name:"Page of Pentacles", image: "pents11.jpg", keywords: ["Curiosity for Things", "Practicality", "Trustworthy"]},
  {name:"Knight of Pentacles", image: "pents12.jpg", keywords: ["Practical ~ Unimaginative", "Persistent ~ Pig-Headed", "Trustworthy ~ Overly Literal / Predictable", "Diligent ~ Obsessive"]},
  {name:"Queen of Pentacles", image: "pents13.jpg", keywords: ["Caring", "Practical", "Of Service"]},
  {name:"King of Pentacles", image: "pents14.jpg", keywords: ["Competent", "Grounded", "All Business"]},
]